[project]
name = "sec-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Qiwei (Emma) Shan", email = "qs2314@columbia.edu" }
]
requires-python = ">=3.13"
dependencies = [
    "edgartools>=5.60.0",
]

[project.scripts]
sec-pipeline = "sec_pipeline:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
